// Mock Database for the Support Portal

const articles = [
    // Mediation
    { id: 1, category: 'Mediation', section: 'SDK', title: 'Getting Started with Mediation', likes: 215, views: 3500, updated: 'Nov 1, 2025', content: 'Your first steps to integrating and configuring the Mediation platform. This guide covers initialization and basic setup. To begin, download the latest SDK from our developer portal and follow the platform-specific instructions for either iOS or Android.' },
    { id: 2, category: 'Mediation', section: 'Platform', title: 'How to Add Ad Sources', likes: 180, views: 2800, updated: 'Oct 28, 2025', content: 'A comprehensive guide to adding and managing different ad network sources within the Mediation platform. This includes setting up bidding networks and traditional waterfall instances.' },
    { id: 3, category: 'Mediation', section: 'Platform', title: 'Understanding Mediation Groups', likes: 155, views: 2400, updated: 'Oct 15, 2025', content: 'Learn how to optimize your ad revenue by using targeted mediation groups and waterfalls. You can segment users by country, device, or other parameters to maximize eCPM.' },
    { id: 4, category: 'Mediation', section: 'General & Account', title: 'Mediation Account Security', likes: 95, views: 1500, updated: 'Oct 10, 2025', content: 'Best practices for keeping your Mediation account secure, including enabling Two-Factor Authentication (2FA) and managing user roles and permissions.' },
    { id: 5, category: 'Mediation', section: 'SDK', title: 'Advanced SDK Features', likes: 130, views: 1900, updated: 'Nov 5, 2025', content: 'Explore advanced features of the SDK, including server-side-to-server callbacks, segmentation, and custom parameters for A/B testing.' },

    // IronSource
    { id: 6, category: 'IronSource', section: 'SDK', title: 'Integrating the IronSource SDK', likes: 198, views: 3200, updated: 'Nov 10, 2025', content: 'Step-by-step instructions for a successful SDK integration on iOS and Android. This article covers dependencies and required adapter initializations.' },
    { id: 7, category: 'IronSource', section: 'Platform', title: 'IronSource Reporting APIs', likes: 140, views: 2600, updated: 'Oct 25, 2025', content: 'How to use the Reporting APIs to pull performance data into your own systems. We provide examples for common API endpoints and authentication methods.' },
    { id: 8, category: 'IronSource', section: 'General & Account', title: 'Payment and Invoicing', likes: 110, views: 2000, updated: 'Oct 5, 2025', content: 'Everything you need to know about payment cycles, invoices, and financial settings in your IronSource account. Find out how to submit your tax forms.' },

    // UnityAds
    { id: 9, category: 'UnityAds', section: 'Platform', title: 'Best Practices for UnityAds Placements', likes: 250, views: 4500, updated: 'Nov 8, 2025', content: 'Tips for maximizing user engagement and revenue with rewarded and interstitial ad placements. Learn where to place ads to improve the user experience.' },
    { id: 10, category: 'UnityAds', section: 'SDK', title: 'Migrating to the new UnityAds SDK', likes: 160, views: 2900, updated: 'Oct 22, 2025', content: 'A guide for developers migrating from older versions of the UnityAds SDK. This includes API changes and new required frameworks.' },
    { id: 11, category: 'UnityAds', section: 'General & Account', title: 'Unity Dashboard Overview', likes: 120, views: 2100, updated: 'Oct 1, 2025', content: 'An overview of the Unity Dashboard for managing your ad monetization, including project settings and ad unit configuration.' },

    // Tapjoy
    { id: 12, category: 'Tapjoy', section: 'Platform', title: 'Setting Up a Tapjoy Offerwall', likes: 175, views: 3100, updated: 'Nov 3, 2025', content: 'A guide to implementing and customizing the Tapjoy Offerwall for your app. This includes setting up virtual currency and managing placements.' },
    { id: 13, category: 'Tapjoy', section: 'SDK', title: 'Tapjoy SDK Integration for iOS', likes: 115, views: 2300, updated: 'Oct 18, 2025', content: 'Detailed instructions for integrating the Tapjoy SDK into your iOS project using Cocoapods or manual installation.' },
    { id: 14, category: 'Tapjoy', section: 'General & Account', title: 'Analyzing Tapjoy Performance', likes: 105, views: 1800, updated: 'Sep 25, 2025', content: 'How to use the Tapjoy dashboard to analyze user engagement and revenue. Learn about cohorts and user segmentation.' },
    
    // More articles for pagination and display
    { id: 15, category: 'Mediation', section: 'SDK', title: 'Debugging Common SDK Issues', likes: 90, views: 1600, updated: 'Sep 20, 2025', content: 'A troubleshooting guide for common issues encountered during SDK integration. Check logs for common error messages.' },
    { id: 16, category: 'UnityAds', section: 'SDK', title: 'Implementing Rewarded Ads', likes: 220, views: 4000, updated: 'Nov 11, 2025', content: 'A detailed walkthrough on how to implement rewarded video ads with Unity. This includes handling callbacks for success and failure.' },
    { id: 17, category: 'Mediation', section: 'Platform', title: 'A/B Testing Best Practices', likes: 145, views: 2500, updated: 'Oct 29, 2025', content: 'Learn how to effectively use A/B testing to optimize your ad monetization strategy. Create variants for your mediation groups.' },
    { id: 18, category: 'IronSource', section: 'Platform', title: 'Setting Up Ad Quality', likes: 135, views: 2450, updated: 'Oct 21, 2025', content: 'Control the quality of ads shown in your app with IronSource Ad Quality tools. Block specific advertisers or categories.' },
    { id: 19, category: 'UnityAds', section: 'Platform', title: 'Understanding eCPM', likes: 190, views: 3300, updated: 'Nov 9, 2025', content: 'A deep dive into what eCPM is and how it affects your revenue. Learn the difference between CPM and eCPM.' },
    { id: 20, category: 'Tapjoy', section: 'Platform', title: 'Customizing Offerwall Currency', likes: 125, views: 2200, updated: 'Oct 12, 2025', content: 'Learn how to set up and manage virtual currency for your Tapjoy Offerwall. This includes setting exchange rates and currency sale events.' },
    
    // Additional articles for pagination
    { id: 21, category: 'Mediation', section: 'SDK', title: 'iOS SDK Integration Guide', likes: 165, views: 2800, updated: 'Nov 12, 2025', content: 'Complete guide for integrating Mediation SDK into your iOS application. Includes Swift and Objective-C examples, dependency management, and configuration steps.' },
    { id: 22, category: 'Mediation', section: 'SDK', title: 'Android SDK Integration Guide', likes: 178, views: 3000, updated: 'Nov 13, 2025', content: 'Step-by-step instructions for integrating Mediation SDK into your Android app. Covers Gradle setup, ProGuard configuration, and initialization code.' },
    { id: 23, category: 'Mediation', section: 'SDK', title: 'Unity Plugin Setup', likes: 142, views: 2200, updated: 'Nov 14, 2025', content: 'How to integrate Mediation into your Unity game project. Learn about the Unity plugin, package installation, and scene configuration.' },
    { id: 24, category: 'Mediation', section: 'SDK', title: 'React Native Integration', likes: 98, views: 1800, updated: 'Nov 15, 2025', content: 'Guide for integrating Mediation SDK into React Native applications. Includes native module setup and JavaScript bridge configuration.' },
    { id: 25, category: 'Mediation', section: 'SDK', title: 'SDK Callbacks and Events', likes: 120, views: 2100, updated: 'Nov 16, 2025', content: 'Understanding SDK callbacks and event handling in Mediation. Learn how to implement ad lifecycle events and error handling.' },
    { id: 26, category: 'Mediation', section: 'SDK', title: 'Testing Your Integration', likes: 88, views: 1600, updated: 'Nov 17, 2025', content: 'Best practices for testing your Mediation SDK integration. Includes test mode configuration, debugging tools, and common test scenarios.' },
    { id: 27, category: 'Mediation', section: 'Platform', title: 'Revenue Optimization Strategies', likes: 200, views: 3800, updated: 'Nov 18, 2025', content: 'Advanced strategies for maximizing your ad revenue with Mediation. Learn about waterfall optimization, bidding strategies, and A/B testing.' },
    { id: 28, category: 'Mediation', section: 'Platform', title: 'Managing Ad Networks', likes: 156, views: 2700, updated: 'Nov 19, 2025', content: 'How to add, configure, and manage multiple ad networks in your Mediation account. Includes network prioritization and performance monitoring.' },
    { id: 29, category: 'Mediation', section: 'Platform', title: 'Waterfall Configuration', likes: 134, views: 2400, updated: 'Nov 20, 2025', content: 'Understanding and configuring waterfall ad delivery in Mediation. Learn how to optimize your waterfall for better fill rates and eCPM.' },
    { id: 30, category: 'Mediation', section: 'Platform', title: 'Bidding Setup and Management', likes: 167, views: 2900, updated: 'Nov 21, 2025', content: 'Complete guide to setting up and managing programmatic bidding in Mediation. Includes header bidding configuration and optimization tips.' },
    { id: 31, category: 'Mediation', section: 'Platform', title: 'Analytics and Reporting', likes: 145, views: 2600, updated: 'Nov 22, 2025', content: 'How to use Mediation analytics and reporting features. Learn about key metrics, custom reports, and data export options.' },
    { id: 32, category: 'Mediation', section: 'Platform', title: 'Ad Format Configuration', likes: 112, views: 2000, updated: 'Nov 23, 2025', content: 'Configuring different ad formats in Mediation including banner, interstitial, and rewarded video ads. Learn format-specific settings and best practices.' },
    { id: 33, category: 'Mediation', section: 'General & Account', title: 'Account Setup and Configuration', likes: 95, views: 1700, updated: 'Nov 24, 2025', content: 'Initial account setup and configuration for Mediation. Includes account verification, payment setup, and basic settings.' },
    { id: 34, category: 'Mediation', section: 'General & Account', title: 'User Roles and Permissions', likes: 78, views: 1400, updated: 'Nov 25, 2025', content: 'Managing user roles and permissions in your Mediation account. Learn how to add team members and assign appropriate access levels.' },
    { id: 35, category: 'Mediation', section: 'General & Account', title: 'Billing and Payment Methods', likes: 102, views: 1900, updated: 'Nov 26, 2025', content: 'Understanding billing cycles, payment methods, and financial settings in Mediation. Learn how to update payment information and view invoices.' },
    { id: 36, category: 'Mediation', section: 'General & Account', title: 'API Access and Keys', likes: 89, views: 1600, updated: 'Nov 27, 2025', content: 'How to generate and manage API keys for Mediation. Includes authentication methods and API usage guidelines.' },
    { id: 37, category: 'Mediation', section: 'General & Account', title: 'Support and Resources', likes: 65, views: 1200, updated: 'Nov 28, 2025', content: 'Available support channels and resources for Mediation users. Learn how to contact support, access documentation, and join community forums.' },
    { id: 38, category: 'Mediation', section: 'General & Account', title: 'Account Migration Guide', likes: 72, views: 1300, updated: 'Nov 29, 2025', content: 'Guide for migrating existing ad network configurations to Mediation. Includes data import, network mapping, and transition strategies.' },
    
    // Additional General & Account articles
    { id: 39, category: 'Mediation', section: 'General & Account', title: 'Two-Factor Authentication Setup', likes: 85, views: 1500, updated: 'Nov 30, 2025', content: 'How to enable and configure Two-Factor Authentication (2FA) for your Mediation account. Learn about authentication apps and backup codes.' },
    { id: 40, category: 'Mediation', section: 'General & Account', title: 'Account Recovery and Password Reset', likes: 68, views: 1200, updated: 'Dec 1, 2025', content: 'Steps to recover your Mediation account if you forget your password or lose access. Includes account verification and security questions.' },
    { id: 41, category: 'Mediation', section: 'General & Account', title: 'Notification Settings and Preferences', likes: 92, views: 1600, updated: 'Dec 2, 2025', content: 'Configure email and in-app notifications for your Mediation account. Manage alerts for payments, performance updates, and system changes.' },
    { id: 42, category: 'Mediation', section: 'General & Account', title: 'Tax Information and Forms', likes: 76, views: 1350, updated: 'Dec 3, 2025', content: 'How to submit tax forms and update tax information in your Mediation account. Learn about W-9, W-8, and international tax requirements.' },
    { id: 43, category: 'Mediation', section: 'General & Account', title: 'Account Limits and Restrictions', likes: 71, views: 1250, updated: 'Dec 4, 2025', content: 'Understanding account limits, restrictions, and compliance requirements in Mediation. Learn about ad network policies and content guidelines.' },
    { id: 44, category: 'Mediation', section: 'General & Account', title: 'Data Export and Backup', likes: 88, views: 1550, updated: 'Dec 5, 2025', content: 'How to export your data and create backups of your Mediation account settings. Includes reporting data export and configuration backups.' },
    { id: 45, category: 'Mediation', section: 'General & Account', title: 'Account Deactivation and Closure', likes: 54, views: 1000, updated: 'Dec 6, 2025', content: 'Process for deactivating or closing your Mediation account. Learn about data retention policies and account closure requirements.' },
    { id: 46, category: 'Mediation', section: 'General & Account', title: 'Multi-Account Management', likes: 97, views: 1700, updated: 'Dec 7, 2025', content: 'Managing multiple Mediation accounts from a single dashboard. Learn about account switching, organization management, and team collaboration.' },
    { id: 47, category: 'Mediation', section: 'General & Account', title: 'Privacy and Data Protection', likes: 82, views: 1450, updated: 'Dec 8, 2025', content: 'Understanding privacy settings and data protection in Mediation. Learn about GDPR compliance, data retention, and user privacy controls.' },
    { id: 48, category: 'Mediation', section: 'General & Account', title: 'Account Verification Process', likes: 90, views: 1650, updated: 'Dec 9, 2025', content: 'Complete guide to verifying your Mediation account. Includes identity verification, business verification, and document submission requirements.' },
    { id: 49, category: 'Mediation', section: 'General & Account', title: 'Subscription Plans and Pricing', likes: 105, views: 1850, updated: 'Dec 10, 2025', content: 'Overview of Mediation subscription plans, pricing tiers, and feature comparisons. Learn about plan upgrades, downgrades, and billing cycles.' },
    { id: 50, category: 'Mediation', section: 'General & Account', title: 'Account Activity and Audit Logs', likes: 79, views: 1400, updated: 'Dec 11, 2025', content: 'How to view and monitor account activity in Mediation. Learn about audit logs, login history, and activity tracking features.' },

    // --- IronSource (additional) ---
    { id: 51, category: 'IronSource', section: 'SDK', title: 'IronSource SDK for Android', likes: 165, views: 2700, updated: 'Dec 5, 2025', content: 'Complete guide to integrating the IronSource SDK in your Android app. Covers Gradle dependencies, initialization, and adapter setup for rewarded and interstitial ads.' },
    { id: 52, category: 'IronSource', section: 'SDK', title: 'IronSource SDK for iOS', likes: 158, views: 2600, updated: 'Dec 4, 2025', content: 'Step-by-step IronSource SDK integration for iOS using Swift or Objective-C. Includes CocoaPods setup, App Transport Security, and SKAdNetwork configuration.' },
    { id: 53, category: 'IronSource', section: 'SDK', title: 'Rewarded Video Implementation', likes: 192, views: 3200, updated: 'Dec 6, 2025', content: 'How to implement rewarded video ads with IronSource. Learn about placement IDs, reward callbacks, and best practices for user engagement.' },
    { id: 54, category: 'IronSource', section: 'Platform', title: 'Campaign Management Basics', likes: 134, views: 2200, updated: 'Dec 2, 2025', content: 'Create and manage user acquisition campaigns in the IronSource platform. Set budgets, targeting, and creative sets for optimal performance.' },
    { id: 55, category: 'IronSource', section: 'Platform', title: 'Understanding ROAS and LTV', likes: 118, views: 1950, updated: 'Dec 1, 2025', content: 'Key metrics for measuring campaign success: Return on Ad Spend (ROAS) and Lifetime Value (LTV). Use these to optimize your user acquisition strategy.' },
    { id: 56, category: 'IronSource', section: 'General & Account', title: 'IronSource Account Setup', likes: 98, views: 1650, updated: 'Nov 28, 2025', content: 'Get your IronSource account up and running. Verification steps, payment details, and connecting your app stores for monetization and user acquisition.' },

    // --- UnityAds (additional) ---
    { id: 57, category: 'UnityAds', section: 'SDK', title: 'Unity Ads SDK for Android', likes: 178, views: 3000, updated: 'Dec 7, 2025', content: 'Integrate Unity Ads into your Android game. Covers the Unity Ads SDK, initialization, and implementing banner, interstitial, and rewarded placements.' },
    { id: 58, category: 'UnityAds', section: 'SDK', title: 'Unity Ads SDK for iOS', likes: 172, views: 2900, updated: 'Dec 6, 2025', content: 'Add Unity Ads to your iOS app. Setup with Swift or Objective-C, configure App Tracking Transparency, and implement ad placements.' },
    { id: 59, category: 'UnityAds', section: 'Platform', title: 'Creating and Managing Ad Units', likes: 145, views: 2500, updated: 'Dec 4, 2025', content: 'Create ad units in the Unity Ads dashboard for monetization and campaigns. Configure placement types, pacing, and geographic targeting.' },
    { id: 60, category: 'UnityAds', section: 'Platform', title: 'Campaign Optimization Tips', likes: 138, views: 2400, updated: 'Dec 3, 2025', content: 'Improve your Unity Ads campaign performance with targeting, creative testing, and bid strategies. Learn how to scale successful campaigns.' },
    { id: 61, category: 'UnityAds', section: 'General & Account', title: 'Payment Thresholds and Payouts', likes: 112, views: 1900, updated: 'Dec 2, 2025', content: 'How Unity Ads payouts work: minimum thresholds, payment methods, and schedule. Set up tax and banking information for timely payments.' },

    // --- Tapjoy (additional) ---
    { id: 62, category: 'Tapjoy', section: 'SDK', title: 'Tapjoy SDK for Android', likes: 122, views: 2100, updated: 'Dec 5, 2025', content: 'Integrate the Tapjoy SDK into your Android app. Configure offerwall and rewarded placements, and handle connection and reward callbacks.' },
    { id: 63, category: 'Tapjoy', section: 'SDK', title: 'Offerwall Implementation Guide', likes: 156, views: 2700, updated: 'Dec 6, 2025', content: 'Implement the Tapjoy Offerwall in your app. Place the offerwall entry point, configure virtual currency, and track user engagement and rewards.' },
    { id: 64, category: 'Tapjoy', section: 'Platform', title: 'Creating Offerwall Placements', likes: 108, views: 1800, updated: 'Dec 3, 2025', content: 'Create and manage Offerwall placements in the Tapjoy dashboard. Set currency, rewards, and targeting to maximize engagement and revenue.' },
    { id: 65, category: 'Tapjoy', section: 'General & Account', title: 'Tapjoy Dashboard Overview', likes: 95, views: 1600, updated: 'Dec 2, 2025', content: 'Navigate the Tapjoy dashboard: revenue reports, user metrics, placement performance, and account settings for publishers and advertisers.' },

    // --- AdQuality ---
    { id: 66, category: 'AdQuality', section: 'SDK', title: 'AdQuality SDK Integration', likes: 142, views: 2400, updated: 'Dec 8, 2025', content: 'Integrate the AdQuality SDK to control ad quality in your app. Block categories, advertisers, or creatives and receive quality signals from the SDK.' },
    { id: 67, category: 'AdQuality', section: 'SDK', title: 'Blocking Low-Quality Ads', likes: 168, views: 2800, updated: 'Dec 7, 2025', content: 'Use AdQuality to block specific advertisers, ad categories, or creatives. Protect user experience while maintaining fill and revenue.' },
    { id: 68, category: 'AdQuality', section: 'Platform', title: 'Ad Quality Dashboard', likes: 125, views: 2100, updated: 'Dec 6, 2025', content: 'Monitor ad quality in the AdQuality dashboard. View block lists, category filters, and quality metrics across your app inventory.' },
    { id: 69, category: 'AdQuality', section: 'Platform', title: 'Category and Advertiser Blocking', likes: 155, views: 2600, updated: 'Dec 5, 2025', content: 'Block entire ad categories or specific advertisers from showing in your app. Configure block lists and allowlists for fine-grained control.' },
    { id: 70, category: 'AdQuality', section: 'Platform', title: 'Quality Signals and Reporting', likes: 98, views: 1700, updated: 'Dec 4, 2025', content: 'Understand quality signals and reports: viewability, brand safety, and user feedback. Use data to refine your blocking and filtering rules.' },
    { id: 71, category: 'AdQuality', section: 'General & Account', title: 'AdQuality Account Setup', likes: 88, views: 1500, updated: 'Dec 3, 2025', content: 'Set up your AdQuality account and connect it to your mediation or ad platform. Configure permissions and default block lists for new apps.' },

    // --- iAds (Monetization & User Acquisition) ---
    { id: 72, category: 'iAds', section: 'SDK', title: 'iAds SDK Integration Overview', likes: 148, views: 2500, updated: 'Dec 9, 2025', content: 'Get started with the iAds SDK for programmatic advertising. Integrate with your iOS or Android app for both monetization and user acquisition.' },
    { id: 73, category: 'iAds', section: 'SDK', title: 'Implementing Programmatic Ads', likes: 135, views: 2300, updated: 'Dec 8, 2025', content: 'Implement programmatic ad formats with the iAds SDK: banner, interstitial, and rewarded. Configure demand sources and handle ad events.' },
    { id: 74, category: 'iAds', section: 'Platform', title: 'iAds Monetization Setup', likes: 162, views: 2700, updated: 'Dec 7, 2025', content: 'Set up iAds for app monetization. Create ad units, configure floor prices, and connect demand partners to maximize your revenue.' },
    { id: 75, category: 'iAds', section: 'Platform', title: 'Running User Acquisition Campaigns', likes: 158, views: 2650, updated: 'Dec 6, 2025', content: 'Launch and optimize user acquisition campaigns with iAds. Target by geography, device, and audience; set budgets and track installs and post-install events.' },
    { id: 76, category: 'iAds', section: 'Platform', title: 'Bidding and Optimization', likes: 128, views: 2150, updated: 'Dec 5, 2025', content: 'How iAds bidding works for monetization and user acquisition. Set bid strategies, use automated optimization, and interpret performance reports.' },
    { id: 77, category: 'iAds', section: 'General & Account', title: 'iAds Account and Billing', likes: 102, views: 1800, updated: 'Dec 4, 2025', content: 'Manage your iAds account: billing, payment methods, and invoices for both publisher earnings and campaign spend. Tax and compliance settings.' },

    // --- General & Account sample articles (additional) ---
    { id: 78, category: 'IronSource', section: 'General & Account', title: 'IronSource User Roles and Permissions', likes: 82, views: 1450, updated: 'Dec 10, 2025', content: 'Add team members and assign roles in your IronSource account. Control who can view reports, manage campaigns, or change billing settings.' },
    { id: 79, category: 'IronSource', section: 'General & Account', title: 'IronSource Two-Factor Authentication', likes: 76, views: 1320, updated: 'Dec 9, 2025', content: 'Enable 2FA for your IronSource account to protect your data and campaigns. Use an authenticator app or backup codes for sign-in.' },
    { id: 80, category: 'IronSource', section: 'General & Account', title: 'Contacting IronSource Support', likes: 95, views: 1680, updated: 'Dec 8, 2025', content: 'How to reach IronSource support: ticket system, live chat, and documentation. Include app IDs and error logs for faster resolution.' },

    { id: 81, category: 'UnityAds', section: 'General & Account', title: 'Unity Ads Account Security', likes: 108, views: 1850, updated: 'Dec 11, 2025', content: 'Keep your Unity Ads account secure with strong passwords, two-factor authentication, and careful management of API keys and user access.' },
    { id: 82, category: 'UnityAds', section: 'General & Account', title: 'Unity Ads Tax and Compliance', likes: 92, views: 1620, updated: 'Dec 10, 2025', content: 'Submit tax forms (W-9, W-8) and manage compliance for Unity Ads payouts. Understand reporting requirements for your region.' },
    { id: 83, category: 'UnityAds', section: 'General & Account', title: 'Unity Ads Support and Documentation', likes: 88, views: 1550, updated: 'Dec 9, 2025', content: 'Access Unity Ads documentation, FAQs, and support. Open a ticket or use the developer community for integration and account help.' },

    { id: 84, category: 'Tapjoy', section: 'General & Account', title: 'Tapjoy Payment and Payouts', likes: 98, views: 1720, updated: 'Dec 12, 2025', content: 'How Tapjoy payouts work: minimum thresholds, payment methods, and schedule. Set up banking and tax information for publisher earnings.' },
    { id: 85, category: 'Tapjoy', section: 'General & Account', title: 'Tapjoy Account Security and 2FA', likes: 72, views: 1280, updated: 'Dec 11, 2025', content: 'Secure your Tapjoy account with two-factor authentication and strong passwords. Manage API keys and user permissions for your team.' },
    { id: 86, category: 'Tapjoy', section: 'General & Account', title: 'Tapjoy Support and Help Resources', likes: 85, views: 1480, updated: 'Dec 10, 2025', content: 'Get help with Tapjoy: contact support, read documentation, and join the publisher community. Troubleshoot integration and account issues.' },

    { id: 87, category: 'AdQuality', section: 'General & Account', title: 'AdQuality User Roles and Access', likes: 78, views: 1380, updated: 'Dec 13, 2025', content: 'Manage who can access your AdQuality account and change block lists. Assign view-only or edit permissions to team members.' },
    { id: 88, category: 'AdQuality', section: 'General & Account', title: 'AdQuality Billing and Plans', likes: 68, views: 1180, updated: 'Dec 12, 2025', content: 'AdQuality subscription plans and billing. Upgrade or downgrade, view invoices, and understand usage-based pricing for your apps.' },
    { id: 89, category: 'AdQuality', section: 'General & Account', title: 'Contact AdQuality Support', likes: 82, views: 1420, updated: 'Dec 11, 2025', content: 'Reach AdQuality support for account, integration, or quality issues. Provide app ID and block list details for faster help.' },

    { id: 90, category: 'iAds', section: 'General & Account', title: 'iAds Account Security and 2FA', likes: 95, views: 1650, updated: 'Dec 14, 2025', content: 'Protect your iAds account with two-factor authentication and secure API keys. Manage user access for monetization and campaign teams.' },
    { id: 91, category: 'iAds', section: 'General & Account', title: 'iAds User Roles and Permissions', likes: 88, views: 1520, updated: 'Dec 13, 2025', content: 'Assign roles in your iAds account: admins, campaign managers, and read-only users. Control who can spend budget or change ad units.' },
    { id: 92, category: 'iAds', section: 'General & Account', title: 'iAds Support and Documentation', likes: 90, views: 1580, updated: 'Dec 12, 2025', content: 'Access iAds documentation, API references, and support. Open a ticket for billing, integration, or campaign optimization help.' }
];
