// Mock Database for the Support Portal

const articles = [
    // LevelPlay
    { id: 1, category: 'LevelPlay', section: 'SDK', title: 'Getting Started with LevelPlay', likes: 215, views: 3500, updated: 'Nov 1, 2025', content: 'Your first steps to integrating and configuring the LevelPlay mediation platform. This guide covers initialization and basic setup. To begin, download the latest SDK from our developer portal and follow the platform-specific instructions for either iOS or Android.' },
    { id: 2, category: 'LevelPlay', section: 'Platform', title: 'How to Add Ad Sources', likes: 180, views: 2800, updated: 'Oct 28, 2025', content: 'A comprehensive guide to adding and managing different ad network sources within the LevelPlay platform. This includes setting up bidding networks and traditional waterfall instances.' },
    { id: 3, category: 'LevelPlay', section: 'Platform', title: 'Understanding Mediation Groups', likes: 155, views: 2400, updated: 'Oct 15, 2025', content: 'Learn how to optimize your ad revenue by using targeted mediation groups and waterfalls. You can segment users by country, device, or other parameters to maximize eCPM.' },
    { id: 4, category: 'LevelPlay', section: 'General & Account', title: 'LevelPlay Account Security', likes: 95, views: 1500, updated: 'Oct 10, 2025', content: 'Best practices for keeping your LevelPlay account secure, including enabling Two-Factor Authentication (2FA) and managing user roles and permissions.' },
    { id: 5, category: 'LevelPlay', section: 'SDK', title: 'Advanced SDK Features', likes: 130, views: 1900, updated: 'Nov 5, 2025', content: 'Explore advanced features of the SDK, including server-side-to-server callbacks, segmentation, and custom parameters for A/B testing.' },

    // IronSource
    { id: 6, category: 'IronSource', section: 'SDK', title: 'Integrating the IronSource SDK', likes: 198, views: 3200, updated: 'Nov 10, 2025', content: 'Step-by-step instructions for a successful SDK integration on iOS and Android. This article covers dependencies and required adapter initializations.' },
    { id: 7, category: 'IronSource', section: 'Platform', title: 'IronSource Reporting APIs', likes: 140, views: 2600, updated: 'Oct 25, 2025', content: 'How to use the Reporting APIs to pull performance data into your own systems. We provide examples for common API endpoints and authentication methods.' },
    { id: 8, category: 'IronSource', section: 'General & Account', title: 'Payment and Invoicing', likes: 110, views: 2000, updated: 'Oct 5, 2025', content: 'Everything you need to know about payment cycles, invoices, and financial settings in your IronSource account. Find out how to submit your tax forms.' },

    // UnityAds
    { id: 9, category: 'UnityAds', section: 'Platform', title: 'Best Practices for UnityAds Placements', likes: 250, views: 4500, updated: 'Nov 8, 2025', content: 'Tips for maximizing user engagement and revenue with rewarded and interstitial ad placements. Learn where to place ads to improve the user experience.' },
    { id: 10, category: 'UnityAds', section: 'SDK', title: 'Migrating to the new UnityAds SDK', likes: 160, views: 2900, updated: 'Oct 22, 2025', content: 'A guide for developers migrating from older versions of the UnityAds SDK. This includes API changes and new required frameworks.' },
    { id: 11, category: 'UnityAds', section: 'General & Account', title: 'Unity Dashboard Overview', likes: 120, views: 2100, updated: 'Oct 1, 2025', content: 'An overview of the Unity Dashboard for managing your ad monetization, including project settings and ad unit configuration.' },

    // Tapjoy
    { id: 12, category: 'Tapjoy', section: 'Platform', title: 'Setting Up a Tapjoy Offerwall', likes: 175, views: 3100, updated: 'Nov 3, 2025', content: 'A guide to implementing and customizing the Tapjoy Offerwall for your app. This includes setting up virtual currency and managing placements.' },
    { id: 13, category: 'Tapjoy', section: 'SDK', title: 'Tapjoy SDK Integration for iOS', likes: 115, views: 2300, updated: 'Oct 18, 2025', content: 'Detailed instructions for integrating the Tapjoy SDK into your iOS project using Cocoapods or manual installation.' },
    { id: 14, category: 'Tapjoy', section: 'General & Account', title: 'Analyzing Tapjoy Performance', likes: 105, views: 1800, updated: 'Sep 25, 2025', content: 'How to use the Tapjoy dashboard to analyze user engagement and revenue. Learn about cohorts and user segmentation.' },
    
    // More articles for pagination and display
    { id: 15, category: 'LevelPlay', section: 'SDK', title: 'Debugging Common SDK Issues', likes: 90, views: 1600, updated: 'Sep 20, 2025', content: 'A troubleshooting guide for common issues encountered during SDK integration. Check logs for common error messages.' },
    { id: 16, category: 'UnityAds', section: 'SDK', title: 'Implementing Rewarded Ads', likes: 220, views: 4000, updated: 'Nov 11, 2025', content: 'A detailed walkthrough on how to implement rewarded video ads with Unity. This includes handling callbacks for success and failure.' },
    { id: 17, category: 'LevelPlay', section: 'Platform', title: 'A/B Testing Best Practices', likes: 145, views: 2500, updated: 'Oct 29, 2025', content: 'Learn how to effectively use A/B testing to optimize your ad monetization strategy. Create variants for your mediation groups.' },
    { id: 18, category: 'IronSource', section: 'Platform', title: 'Setting Up Ad Quality', likes: 135, views: 2450, updated: 'Oct 21, 2025', content: 'Control the quality of ads shown in your app with IronSource Ad Quality tools. Block specific advertisers or categories.' },
    { id: 19, category: 'UnityAds', section: 'Platform', title: 'Understanding eCPM', likes: 190, views: 3300, updated: 'Nov 9, 2025', content: 'A deep dive into what eCPM is and how it affects your revenue. Learn the difference between CPM and eCPM.' },
    { id: 20, category: 'Tapjoy', section: 'Platform', title: 'Customizing Offerwall Currency', likes: 125, views: 2200, updated: 'Oct 12, 2025', content: 'Learn how to set up and manage virtual currency for your Tapjoy Offerwall. This includes setting exchange rates and currency sale events.' },
    
    // Additional articles for pagination
    { id: 21, category: 'LevelPlay', section: 'SDK', title: 'iOS SDK Integration Guide', likes: 165, views: 2800, updated: 'Nov 12, 2025', content: 'Complete guide for integrating LevelPlay SDK into your iOS application. Includes Swift and Objective-C examples, dependency management, and configuration steps.' },
    { id: 22, category: 'LevelPlay', section: 'SDK', title: 'Android SDK Integration Guide', likes: 178, views: 3000, updated: 'Nov 13, 2025', content: 'Step-by-step instructions for integrating LevelPlay SDK into your Android app. Covers Gradle setup, ProGuard configuration, and initialization code.' },
    { id: 23, category: 'LevelPlay', section: 'SDK', title: 'Unity Plugin Setup', likes: 142, views: 2200, updated: 'Nov 14, 2025', content: 'How to integrate LevelPlay mediation into your Unity game project. Learn about the Unity plugin, package installation, and scene configuration.' },
    { id: 24, category: 'LevelPlay', section: 'SDK', title: 'React Native Integration', likes: 98, views: 1800, updated: 'Nov 15, 2025', content: 'Guide for integrating LevelPlay SDK into React Native applications. Includes native module setup and JavaScript bridge configuration.' },
    { id: 25, category: 'LevelPlay', section: 'SDK', title: 'SDK Callbacks and Events', likes: 120, views: 2100, updated: 'Nov 16, 2025', content: 'Understanding SDK callbacks and event handling in LevelPlay. Learn how to implement ad lifecycle events and error handling.' },
    { id: 26, category: 'LevelPlay', section: 'SDK', title: 'Testing Your Integration', likes: 88, views: 1600, updated: 'Nov 17, 2025', content: 'Best practices for testing your LevelPlay SDK integration. Includes test mode configuration, debugging tools, and common test scenarios.' },
    { id: 27, category: 'LevelPlay', section: 'Platform', title: 'Revenue Optimization Strategies', likes: 200, views: 3800, updated: 'Nov 18, 2025', content: 'Advanced strategies for maximizing your ad revenue with LevelPlay. Learn about waterfall optimization, bidding strategies, and A/B testing.' },
    { id: 28, category: 'LevelPlay', section: 'Platform', title: 'Managing Ad Networks', likes: 156, views: 2700, updated: 'Nov 19, 2025', content: 'How to add, configure, and manage multiple ad networks in your LevelPlay account. Includes network prioritization and performance monitoring.' },
    { id: 29, category: 'LevelPlay', section: 'Platform', title: 'Waterfall Configuration', likes: 134, views: 2400, updated: 'Nov 20, 2025', content: 'Understanding and configuring waterfall ad delivery in LevelPlay. Learn how to optimize your waterfall for better fill rates and eCPM.' },
    { id: 30, category: 'LevelPlay', section: 'Platform', title: 'Bidding Setup and Management', likes: 167, views: 2900, updated: 'Nov 21, 2025', content: 'Complete guide to setting up and managing programmatic bidding in LevelPlay. Includes header bidding configuration and optimization tips.' },
    { id: 31, category: 'LevelPlay', section: 'Platform', title: 'Analytics and Reporting', likes: 145, views: 2600, updated: 'Nov 22, 2025', content: 'How to use LevelPlay analytics and reporting features. Learn about key metrics, custom reports, and data export options.' },
    { id: 32, category: 'LevelPlay', section: 'Platform', title: 'Ad Format Configuration', likes: 112, views: 2000, updated: 'Nov 23, 2025', content: 'Configuring different ad formats in LevelPlay including banner, interstitial, and rewarded video ads. Learn format-specific settings and best practices.' },
    { id: 33, category: 'LevelPlay', section: 'General & Account', title: 'Account Setup and Configuration', likes: 95, views: 1700, updated: 'Nov 24, 2025', content: 'Initial account setup and configuration for LevelPlay. Includes account verification, payment setup, and basic settings.' },
    { id: 34, category: 'LevelPlay', section: 'General & Account', title: 'User Roles and Permissions', likes: 78, views: 1400, updated: 'Nov 25, 2025', content: 'Managing user roles and permissions in your LevelPlay account. Learn how to add team members and assign appropriate access levels.' },
    { id: 35, category: 'LevelPlay', section: 'General & Account', title: 'Billing and Payment Methods', likes: 102, views: 1900, updated: 'Nov 26, 2025', content: 'Understanding billing cycles, payment methods, and financial settings in LevelPlay. Learn how to update payment information and view invoices.' },
    { id: 36, category: 'LevelPlay', section: 'General & Account', title: 'API Access and Keys', likes: 89, views: 1600, updated: 'Nov 27, 2025', content: 'How to generate and manage API keys for LevelPlay. Includes authentication methods and API usage guidelines.' },
    { id: 37, category: 'LevelPlay', section: 'General & Account', title: 'Support and Resources', likes: 65, views: 1200, updated: 'Nov 28, 2025', content: 'Available support channels and resources for LevelPlay users. Learn how to contact support, access documentation, and join community forums.' },
    { id: 38, category: 'LevelPlay', section: 'General & Account', title: 'Account Migration Guide', likes: 72, views: 1300, updated: 'Nov 29, 2025', content: 'Guide for migrating existing ad network configurations to LevelPlay. Includes data import, network mapping, and transition strategies.' },
    
    // Additional General & Account articles
    { id: 39, category: 'LevelPlay', section: 'General & Account', title: 'Two-Factor Authentication Setup', likes: 85, views: 1500, updated: 'Nov 30, 2025', content: 'How to enable and configure Two-Factor Authentication (2FA) for your LevelPlay account. Learn about authentication apps and backup codes.' },
    { id: 40, category: 'LevelPlay', section: 'General & Account', title: 'Account Recovery and Password Reset', likes: 68, views: 1200, updated: 'Dec 1, 2025', content: 'Steps to recover your LevelPlay account if you forget your password or lose access. Includes account verification and security questions.' },
    { id: 41, category: 'LevelPlay', section: 'General & Account', title: 'Notification Settings and Preferences', likes: 92, views: 1600, updated: 'Dec 2, 2025', content: 'Configure email and in-app notifications for your LevelPlay account. Manage alerts for payments, performance updates, and system changes.' },
    { id: 42, category: 'LevelPlay', section: 'General & Account', title: 'Tax Information and Forms', likes: 76, views: 1350, updated: 'Dec 3, 2025', content: 'How to submit tax forms and update tax information in your LevelPlay account. Learn about W-9, W-8, and international tax requirements.' },
    { id: 43, category: 'LevelPlay', section: 'General & Account', title: 'Account Limits and Restrictions', likes: 71, views: 1250, updated: 'Dec 4, 2025', content: 'Understanding account limits, restrictions, and compliance requirements in LevelPlay. Learn about ad network policies and content guidelines.' },
    { id: 44, category: 'LevelPlay', section: 'General & Account', title: 'Data Export and Backup', likes: 88, views: 1550, updated: 'Dec 5, 2025', content: 'How to export your data and create backups of your LevelPlay account settings. Includes reporting data export and configuration backups.' },
    { id: 45, category: 'LevelPlay', section: 'General & Account', title: 'Account Deactivation and Closure', likes: 54, views: 1000, updated: 'Dec 6, 2025', content: 'Process for deactivating or closing your LevelPlay account. Learn about data retention policies and account closure requirements.' },
    { id: 46, category: 'LevelPlay', section: 'General & Account', title: 'Multi-Account Management', likes: 97, views: 1700, updated: 'Dec 7, 2025', content: 'Managing multiple LevelPlay accounts from a single dashboard. Learn about account switching, organization management, and team collaboration.' },
    { id: 47, category: 'LevelPlay', section: 'General & Account', title: 'Privacy and Data Protection', likes: 82, views: 1450, updated: 'Dec 8, 2025', content: 'Understanding privacy settings and data protection in LevelPlay. Learn about GDPR compliance, data retention, and user privacy controls.' },
    { id: 48, category: 'LevelPlay', section: 'General & Account', title: 'Account Verification Process', likes: 90, views: 1650, updated: 'Dec 9, 2025', content: 'Complete guide to verifying your LevelPlay account. Includes identity verification, business verification, and document submission requirements.' },
    { id: 49, category: 'LevelPlay', section: 'General & Account', title: 'Subscription Plans and Pricing', likes: 105, views: 1850, updated: 'Dec 10, 2025', content: 'Overview of LevelPlay subscription plans, pricing tiers, and feature comparisons. Learn about plan upgrades, downgrades, and billing cycles.' },
    { id: 50, category: 'LevelPlay', section: 'General & Account', title: 'Account Activity and Audit Logs', likes: 79, views: 1400, updated: 'Dec 11, 2025', content: 'How to view and monitor account activity in LevelPlay. Learn about audit logs, login history, and activity tracking features.' }
];
